apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "usora-notification-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usora-notification-service.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile | quote }}

  DB_HOST: {{ .Values.postgresql.host | quote }}
  DB_PORT: {{ .Values.postgresql.port | quote }}
  DB_NAME: {{ .Values.postgresql.database | quote }}

  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}

  TENANT_SERVICE_HOST: {{ .Values.tenantService.serviceName | quote }}
  TENANT_SERVICE_PORT: {{ .Values.tenantService.port | quote }}

  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
