// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureValue {
    #[prost(oneof = "feature_value::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<feature_value::Value>,
}
/// Nested message and enum types in `FeatureValue`.
pub mod feature_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringVal(::prost::alloc::string::String),
        #[prost(int64, tag = "2")]
        IntVal(i64),
        #[prost(double, tag = "3")]
        FloatVal(f64),
        #[prost(bool, tag = "4")]
        BoolVal(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeatureContribution {
    #[prost(string, tag = "1")]
    pub feature_name: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub importance: f64,
    #[prost(double, tag = "3")]
    pub shap_value: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScoreExplanation {
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub base_score: f64,
    #[prost(message, repeated, tag = "3")]
    pub feature_contributions: ::prost::alloc::vec::Vec<FeatureContribution>,
    #[prost(string, repeated, tag = "4")]
    pub top_risk_drivers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(double, tag = "5")]
    pub confidence: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskFactor {
    #[prost(string, tag = "1")]
    pub factor_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub factor_type: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub severity: f64,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub source: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScoringResponse {
    #[prost(string, tag = "1")]
    pub score_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub applicant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub composite_score: f64,
    #[prost(string, tag = "5")]
    pub risk_level: ::prost::alloc::string::String,
    #[prost(double, tag = "6")]
    pub ml_score: f64,
    #[prost(double, tag = "7")]
    pub rule_score: f64,
    #[prost(string, tag = "8")]
    pub model_version: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub rule_version: ::prost::alloc::string::String,
    #[prost(double, tag = "10")]
    pub processing_time_ms: f64,
    #[prost(string, tag = "11")]
    pub computed_at: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "12")]
    pub explanation: ::core::option::Option<ScoreExplanation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplicantScoringRequest {
    #[prost(string, tag = "1")]
    pub applicant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "3")]
    pub features: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        FeatureValue,
    >,
    #[prost(bool, tag = "4")]
    pub include_explanation: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplicantScoringResponse {
    #[prost(message, optional, tag = "1")]
    pub response: ::core::option::Option<ScoringResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionScoringRequest {
    #[prost(string, tag = "1")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub applicant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(double, tag = "4")]
    pub amount: f64,
    #[prost(string, tag = "5")]
    pub currency: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub transaction_type: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "7")]
    pub features: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        FeatureValue,
    >,
    #[prost(int64, tag = "8")]
    pub timestamp_seconds: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionScoringResponse {
    #[prost(message, optional, tag = "1")]
    pub response: ::core::option::Option<ScoringResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskFactorsRequest {
    #[prost(string, tag = "1")]
    pub score_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub applicant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskFactorsResponse {
    #[prost(string, tag = "1")]
    pub score_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub risk_factors: ::prost::alloc::vec::Vec<RiskFactor>,
    #[prost(double, tag = "3")]
    pub total_risk_score: f64,
    #[prost(string, tag = "4")]
    pub risk_level: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelUpdateRequest {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub model_path: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub checksum: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub force: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelUpdateResponse {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub previous_version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub current_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub reloaded_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExplainabilityRequest {
    #[prost(string, tag = "1")]
    pub score_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub applicant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub max_features: u32,
    #[prost(double, tag = "5")]
    pub min_importance: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExplainabilityResponse {
    #[prost(string, tag = "1")]
    pub score_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub explanation: ::core::option::Option<ScoreExplanation>,
    #[prost(string, tag = "3")]
    pub model_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub rule_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchScoringRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub requests: ::prost::alloc::vec::Vec<ApplicantScoringRequest>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchScoringResponse {
    #[prost(message, repeated, tag = "1")]
    pub responses: ::prost::alloc::vec::Vec<ScoringResponse>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RiskLevel {
    Unspecified = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}
impl RiskLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RISK_LEVEL_UNSPECIFIED",
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
            Self::Critical => "CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RISK_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "LOW" => Some(Self::Low),
            "MEDIUM" => Some(Self::Medium),
            "HIGH" => Some(Self::High),
            "CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod risk_scoring_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct RiskScoringServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RiskScoringServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RiskScoringServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RiskScoringServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RiskScoringServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn score_applicant(
            &mut self,
            request: impl tonic::IntoRequest<super::ApplicantScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApplicantScoringResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/ScoreApplicant",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("risk_scoring.RiskScoringService", "ScoreApplicant"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn score_transaction(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionScoringResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/ScoreTransaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "risk_scoring.RiskScoringService",
                        "ScoreTransaction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_risk_factors(
            &mut self,
            request: impl tonic::IntoRequest<super::RiskFactorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RiskFactorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/GetRiskFactors",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("risk_scoring.RiskScoringService", "GetRiskFactors"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_risk_model(
            &mut self,
            request: impl tonic::IntoRequest<super::ModelUpdateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ModelUpdateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/UpdateRiskModel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("risk_scoring.RiskScoringService", "UpdateRiskModel"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn explain_risk_score(
            &mut self,
            request: impl tonic::IntoRequest<super::ExplainabilityRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExplainabilityResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/ExplainRiskScore",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "risk_scoring.RiskScoringService",
                        "ExplainRiskScore",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn batch_score_applicants(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchScoringResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/risk_scoring.RiskScoringService/BatchScoreApplicants",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "risk_scoring.RiskScoringService",
                        "BatchScoreApplicants",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod risk_scoring_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RiskScoringServiceServer.
    #[async_trait]
    pub trait RiskScoringService: std::marker::Send + std::marker::Sync + 'static {
        async fn score_applicant(
            &self,
            request: tonic::Request<super::ApplicantScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApplicantScoringResponse>,
            tonic::Status,
        >;
        async fn score_transaction(
            &self,
            request: tonic::Request<super::TransactionScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionScoringResponse>,
            tonic::Status,
        >;
        async fn get_risk_factors(
            &self,
            request: tonic::Request<super::RiskFactorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RiskFactorsResponse>,
            tonic::Status,
        >;
        async fn update_risk_model(
            &self,
            request: tonic::Request<super::ModelUpdateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ModelUpdateResponse>,
            tonic::Status,
        >;
        async fn explain_risk_score(
            &self,
            request: tonic::Request<super::ExplainabilityRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExplainabilityResponse>,
            tonic::Status,
        >;
        async fn batch_score_applicants(
            &self,
            request: tonic::Request<super::BatchScoringRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BatchScoringResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct RiskScoringServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RiskScoringServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RiskScoringServiceServer<T>
    where
        T: RiskScoringService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/risk_scoring.RiskScoringService/ScoreApplicant" => {
                    #[allow(non_camel_case_types)]
                    struct ScoreApplicantSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::ApplicantScoringRequest>
                    for ScoreApplicantSvc<T> {
                        type Response = super::ApplicantScoringResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ApplicantScoringRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::score_applicant(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ScoreApplicantSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/risk_scoring.RiskScoringService/ScoreTransaction" => {
                    #[allow(non_camel_case_types)]
                    struct ScoreTransactionSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::TransactionScoringRequest>
                    for ScoreTransactionSvc<T> {
                        type Response = super::TransactionScoringResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TransactionScoringRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::score_transaction(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ScoreTransactionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/risk_scoring.RiskScoringService/GetRiskFactors" => {
                    #[allow(non_camel_case_types)]
                    struct GetRiskFactorsSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::RiskFactorsRequest>
                    for GetRiskFactorsSvc<T> {
                        type Response = super::RiskFactorsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RiskFactorsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::get_risk_factors(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetRiskFactorsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/risk_scoring.RiskScoringService/UpdateRiskModel" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateRiskModelSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::ModelUpdateRequest>
                    for UpdateRiskModelSvc<T> {
                        type Response = super::ModelUpdateResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ModelUpdateRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::update_risk_model(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateRiskModelSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/risk_scoring.RiskScoringService/ExplainRiskScore" => {
                    #[allow(non_camel_case_types)]
                    struct ExplainRiskScoreSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::ExplainabilityRequest>
                    for ExplainRiskScoreSvc<T> {
                        type Response = super::ExplainabilityResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExplainabilityRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::explain_risk_score(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExplainRiskScoreSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/risk_scoring.RiskScoringService/BatchScoreApplicants" => {
                    #[allow(non_camel_case_types)]
                    struct BatchScoreApplicantsSvc<T: RiskScoringService>(pub Arc<T>);
                    impl<
                        T: RiskScoringService,
                    > tonic::server::UnaryService<super::BatchScoringRequest>
                    for BatchScoreApplicantsSvc<T> {
                        type Response = super::BatchScoringResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BatchScoringRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RiskScoringService>::batch_score_applicants(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BatchScoreApplicantsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RiskScoringServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "risk_scoring.RiskScoringService";
    impl<T> tonic::server::NamedService for RiskScoringServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
