{{- if gt (int (.Values.autoscaling.minReplicas | default .Values.replicaCount)) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "usora-document-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usora-document-processor.labels" . | nindent 4 }}
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      {{- include "usora-document-processor.selectorLabels" . | nindent 6 }}
{{- end }}
