{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "usora-risk-scoring-engine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usora-risk-scoring-engine.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
